import { useEffect, useState } from "react";
import styles from "../../styles/Checkout.module.css";
import { Row, Col, Card, Button, Form } from 'react-bootstrap'
import Head from 'next/head'
import * as commonConstants from '../../logic/common-constants'
import Link from "next/link";


import { useCart } from "../../context/CartContext";
import { useLanguage } from "../../context/LanguageContext";
import FormField from "../../components/FormField";

const Checkout = () => {

    const { cart, makeOrder } = useCart()
    const { translate } = useLanguage();
    const [loading, setLoading] = useState(true);

    const [first_name, setFirstName] = useState('')
    const [last_name, setLastName] = useState('')
    const [email, setEmail] = useState('')
    const [phone, setPhone] = useState('')

    const [street, setStreet] = useState('')
    const [apt, setApt] = useState('')
    const [city, setCity] = useState('')
    const [usa_state, setUsaState] = useState('')
    const [zipCode, setZipCode] = useState('')

    const [card_number, setCardNumber] = useState('')
    const [card_expMonth, setCardExpMonth] = useState('')
    const [card_expYear, setCardExpYear] = useState('')
    const [card_cvc, setCardCvc] = useState('')

    const [orderResult, setOrderResult] = useState(null);
    const [message, setMessage] = useState('');

    useEffect(() => {
        if (cart !== null && cart !== undefined) {
            setLoading(false)
        }
    }, [cart])

    const onCreateOrder = async (e) => {
        e.preventDefault();
        const body = JSON.stringify({
            cart: cart.id,
            first_name,
            last_name,
            email,
            phone,
            shipping_address: {
                street,
                apt_suite: apt,
                city,
                zip_code: zipCode,
                usa_state
            },
            card_num: card_number,
            exp_month: card_expMonth,
            exp_year: card_expYear,
            cvc: card_cvc
        })
        await makeOrder(body, setOrderResult)
    }

    useEffect(() => {
        if (orderResult === 'Success') {
            setMessage('Success')
        }
        if (orderResult === 'Error') {
            setMessage('Error during payment')
        }
    }, [orderResult])

    return (loading) ? <div>No order for checkout</div> : (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.checkout_wrapper}>

                    <div className={styles.checkout_title_div}>
                        <h2 className={styles.checkout_title}>
                            {translate('word', 'checkout', 'partial')}
                        </h2>
                    </div>

                    {orderResult === 'Error' ?
                        <div className={styles.checkout_error_div}>
                          <p className={styles.checkout_error_description}><span className={styles.checkout_error}>Error: </span>An error occurred during payment. Please check the information
                          and try again. If the error persist, please contact the store admin at <span className={styles.checkout_error_link}>sales@habanerasdelino.com</span></p> 
                        </div>
                        :
                        <div></div>
                    }

                    <div className={styles.checkout_form_div}>
                        <Row className={styles.checkout_row}>
                            <Col xs={12} sm={12} md={6} lg={6} className={styles.payment_col}>
                                <div className={styles.shipping_info_div}>

                                    <div className={styles.shipping_info_row_div}>
                                        <Row className={styles.shipping_info_row}>
                                            <Col xs={6} sm={6} md={6} lg={6}>
                                                <FormField title='First Name' placeholder='First Name' value={first_name} setValue={setFirstName} valueType='text' />
                                            </Col>

                                            <Col xs={6} sm={6} md={6} lg={6}>
                                                <FormField title='Last Name' placeholder='Last Name' value={last_name} setValue={setLastName} valueType='text' />
                                            </Col>
                                        </Row>
                                    </div>

                                    <div className={styles.shipping_info_row_div}>
                                        <Row className={styles.shipping_info_row}>
                                            <FormField title='Email' placeholder='Email@example.com' value={email} setValue={setEmail} valueType='email' />
                                        </Row>
                                    </div>


                                    <div className={styles.shipping_info_row_div}>
                                        <Row className={styles.shipping_info_row}>
                                            <FormField title='Phone' placeholder='xxx-xxx-xxxx' value={phone} setValue={setPhone} valueType='text' />
                                        </Row>
                                    </div>

                                </div>


                                <div className={styles.divider} />

                                <div className={styles.shipping_info_div}>
                                    <h4 className={styles.section_title}>{translate('short phrase', 'shipping_info', 'partial')}</h4>
                                    <div className={styles.shipping_info_row_div}>
                                        <Row className={styles.shipping_info_row}>
                                            <Col xs={6} sm={6} md={6} lg={6}>
                                                <FormField title='Street Address' placeholder='123 28th St West' value={street} setValue={setStreet} valueType='text' />
                                            </Col>

                                            <Col xs={6} sm={6} md={6} lg={6}>
                                                <FormField title='Apt/Suite/Floor' placeholder='Apt 401' value={apt} setValue={setApt} valueType='text' />
                                            </Col>
                                        </Row>
                                    </div>

                                    <div className={styles.shipping_info_row_div}>
                                        <Row className={styles.shipping_info_row}>
                                            <Col xs={4} sm={4} md={4} lg={4}>
                                                <FormField title='City' placeholder='City' value={city} setValue={setCity} valueType='text' />
                                            </Col>
                                            <Col xs={4} sm={4} md={4} lg={4}>
                                                <FormField title='State' placeholder='TEXAS' value={usa_state} setValue={setUsaState} valueType='text' />
                                            </Col>
                                            <Col xs={4} sm={4} md={4} lg={4}>
                                                <FormField title='Zip Code' placeholder='12345' value={zipCode} setValue={setZipCode} valueType='text' />
                                            </Col>
                                        </Row>
                                    </div>

                                </div>


                                <div className={styles.divider} />

                                <div className={styles.shipping_info_div}>
                                    <h4 className={styles.section_title}>{translate('short phrase', 'billing_info', 'partial')}</h4>

                                    <div className={styles.shipping_info_row_div}>
                                        <Row className={styles.shipping_info_row}>
                                            <FormField title='Card Number' placeholder='xxxxxxxxxxxxxxxx' value={card_number} setValue={setCardNumber} valueType='text' />
                                        </Row>
                                    </div>

                                    <div className={styles.shipping_info_row_div}>
                                        <Row className={styles.shipping_info_row}>
                                            <Col xs={4} sm={4} md={4} lg={4}>
                                                <FormField title='Exp Month' placeholder='01' value={card_expMonth} setValue={setCardExpMonth} valueType='text' />
                                            </Col>
                                            <Col xs={4} sm={4} md={4} lg={4}>
                                                <FormField title='Exp Year' placeholder='26' value={card_expYear} setValue={setCardExpYear} valueType='text' />
                                            </Col>
                                            <Col xs={4} sm={4} md={4} lg={4}>
                                                <FormField title='CVC' placeholder='123' value={card_cvc} setValue={setCardCvc} valueType='text' />
                                            </Col>
                                        </Row>
                                    </div>
                                </div>
                            </Col>

                            <Col xs={12} sm={12} md={6} lg={6} className={styles.information_col}>

                                <div className={styles.checkout_info_div}>
                                    <Card className={styles.checkout_info_card}>
                                        <h4 className={styles.section_title}>{translate('short phrase', 'purchase_info', 'partial')}</h4>

                                        <p className={styles.checkout_info_p}><span className={styles.checkout_info_p_span}>
                                            Subtotal: </span> ${cart ? parseFloat(cart.total_amount).toFixed(2) : "0.00"}
                                        </p>

                                        <p className={styles.checkout_info_p}><span className={styles.checkout_info_p_span}>
                                            Taxes: </span> ${cart ? parseFloat(parseFloat(cart.total_amount) * 0.07).toFixed(2) : "0.00"}
                                        </p>

                                        <p className={styles.checkout_info_p}><span className={styles.checkout_info_p_span}>
                                            Total (Taxes + Shipping): </span> ${cart ?
                                                parseFloat(parseFloat(cart.total_amount) + parseFloat(cart.total_amount) * 0.07).toFixed(2) : "0.00"
                                            }
                                        </p>

                                    </Card>



                                    <div className={styles.purchase_div}>
                                        <Button variant='dark' className={styles.purchase_button} onClick={(e) => onCreateOrder(e)}>
                                            {translate('short phrase', 'make_purchase', 'partial')}
                                        </Button>
                                    </div>
                                </div>
                            </Col>
                        </Row>
                    </div>
                </div>
            </main>
        </>
    );

}

export default Checkout;